# Generated by Django 5.0.6 on 2024-06-20 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('car_title', models.CharField(max_length=255)),
                ('customer_needs', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('I_ID', models.IntegerField()),
                ('car_ID', models.IntegerField()),
                ('user_ID', models.IntegerField(blank=True)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
