# Generated by Django 5.0.6 on 2024-06-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_rename_contactus_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='I_ID',
        ),
    ]
