# Generated by Django 5.0.6 on 2024-06-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 9, 20, 54, 961341)),
        ),
    ]
