# Generated by Django 5.0.6 on 2024-07-12 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_car_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 37, 49, 576656)),
        ),
    ]
